# Generated by Django 4.2.18 on 2025-08-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description_corta', models.CharField(max_length=200, verbose_name='Descripción Corta')),
                ('description_larga', models.TextField(verbose_name='Descripción Larga')),
                ('thumbnail_url', models.URLField(verbose_name='URL de Miniatura')),
                ('accepts_files', models.BooleanField(default=False, verbose_name='Acepta archivos')),
                ('accepts_text', models.BooleanField(default=False, verbose_name='Acepta texto')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='Categoría')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='Etiquetas (separadas por coma)')),
                ('extra_fields', models.JSONField(blank=True, null=True, verbose_name='Campos extra para el formulario')),
                ('politica_datos_url', models.URLField(blank=True, verbose_name='URL de política de datos')),
            ],
            options={
                'verbose_name': 'Demo',
                'verbose_name_plural': 'Demos',
            },
        ),
    ]
