# Generated by Django 4.2.18 on 2025-08-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Título SEO (meta title)')),
                ('meta_description', models.TextField(blank=True, max_length=300, null=True, verbose_name='Descripción SEO (meta description)')),
                ('meta_keywords', models.CharField(blank=True, max_length=200, null=True, verbose_name='Palabras clave SEO')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Proyecto')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('resumen', models.CharField(max_length=250, verbose_name='Resumen')),
                ('cover_url', models.URLField(verbose_name='URL de Portada')),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha de Publicación')),
                ('reto', models.TextField(verbose_name='Reto')),
                ('enfoque', models.TextField(verbose_name='Enfoque')),
                ('kpis', models.JSONField(blank=True, null=True, verbose_name='Resultados (KPIs)')),
                ('stack', models.CharField(max_length=250, verbose_name='Stack Tecnológico')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='URL de Video')),
                ('demo_slug', models.SlugField(blank=True, max_length=100, null=True, verbose_name='Slug de demo relacionada')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
    ]
