# Generated by Django 4.2.18 on 2025-08-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Título SEO (meta title)')),
                ('meta_description', models.TextField(blank=True, max_length=300, null=True, verbose_name='Descripción SEO (meta description)')),
                ('meta_keywords', models.CharField(blank=True, max_length=200, null=True, verbose_name='Palabras clave SEO')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Servicio')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('hero_heading', models.CharField(max_length=250, verbose_name='Título del Hero')),
                ('hero_subheading', models.TextField(verbose_name='Subtítulo del Hero')),
                ('problema', models.TextField(verbose_name='Sección: El problema')),
                ('solucion', models.TextField(verbose_name='Sección: Nuestra solución')),
                ('beneficios', models.JSONField(verbose_name='Sección: Beneficios')),
                ('como_trabajo', models.JSONField(verbose_name='Sección: Cómo trabajo (pasos)')),
                ('faq', models.JSONField(verbose_name='Sección: Preguntas frecuentes')),
                ('demos_relacionadas', models.ManyToManyField(blank=True, to='demos.appdemo', verbose_name='Demos relacionadas')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
    ]
