# Generated by Django 4.2.18 on 2025-08-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Título SEO (meta title)')),
                ('meta_description', models.TextField(blank=True, max_length=300, null=True, verbose_name='Descripción SEO (meta description)')),
                ('meta_keywords', models.CharField(blank=True, max_length=200, null=True, verbose_name='Palabras clave SEO')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('excerpt', models.CharField(max_length=250, verbose_name='Extracto')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('published_at', models.DateTimeField(verbose_name='Fecha de Publicación')),
                ('cover_url', models.URLField(verbose_name='URL de Portada')),
                ('author_name', models.CharField(default='Equipo', max_length=100, verbose_name='Autor')),
                ('read_time', models.IntegerField(verbose_name='Tiempo de lectura (min)')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['-published_at'],
            },
        ),
    ]
